### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by Yash-Singh-Pathania** [alokm014/Gesture-Controlled-Mouse#1]
This error along with seeing just a black screen pops up during calibration

**Comment by alokm014** [comment]
The problem is in this line:

`_,contour, _ = cv2.findContours( mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`

Change it to:

`contour, _ = cv2.findContours( mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`
