### ISSUE TITLE
#error 

### ISSUE THREAD

**Issue by anveshduddu** [alokm014/Gesture-Controlled-Mouse#2]
OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-kh7iq4w7\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by alokm014** [comment]
Error: !_src.empty() in function 'cv::cvtColor means the object passed to function cvtColor is empty or say none. Check your WebCam.
